version: '3.8'  

services:    
  db:  
    image: mysql:latest  
    restart: always  
    environment:  
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: mydatabase  
      MYSQL_USER: user  
      MYSQL_PASSWORD: userpassword  
    ports:  
      - "3307:3307"  
    volumes:  
      - mysql_data:/var/lib/mysql 

volumes:  
  mysql_data: